import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { NoUserProvider } from "@/contexts/NoUserContext";
import { LoginFormProvider } from "@/contexts/LoginFormContext";
import { VerifyOTPProvider } from "@/contexts/VerifyOTPContext";
import { VerifyOTPProvider2 } from "@/contexts/VerifyOTPContext2";

const notoSans = Noto_Sans({
  subsets: ["latin"], // Add subsets as needed
  weight: ["400", "600", "700"], // Specify weights
  style: ["normal", "italic"], // Specify styles
});

export const metadata: Metadata = {
  title: "save bite | home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <VerifyOTPProvider2>
      <VerifyOTPProvider>
        <LoginFormProvider>
          <NoUserProvider>
            <html lang="en" className={notoSans.className}>
              <body
                className={`antialiased min-h-screen`}
                suppressHydrationWarning={true}
              >
                {children}
              </body>
            </html>
          </NoUserProvider>
        </LoginFormProvider>
      </VerifyOTPProvider>
    </VerifyOTPProvider2>
  );
}
