import type { Metadata } from "next";
import Image from "next/image";
import Link from "next/link";
import NavBar from "../../../../components/NavBar";
import SignupForm from "../../../../components/SignupForm";

export const metadata: Metadata = {
  title: "save bite | Signup",
  description: "Generated by create next app",
};

export default function authLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` min-h-screen`}>
      <NavBar />
      <div className="mx-auto text-center font-medium">
        <p className="pt-[40px] pb-[16px] text-[28px]">Create a Savebite account</p>
        <p className="text-[19px]">
          Already have an account?
          <Link href={"/login"} className="pl-[8px] text-primary-500">Login</Link>
        </p>
      </div>
        <SignupForm />
      {children}
    </div>
  );
}
