import type { Metadata } from "next";
import "./globals.css";
import { Noto_Sans } from "next/font/google";
import { VerifyOTPProvider } from "@/contexts/VerifyOTPContext";
import { VerifyOTPProvider2 } from "@/contexts/VerifyOTPContext2";
import { NextIntlClientProvider } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";
import { getMessages } from "next-intl/server";

const notoSans = Noto_Sans({
  subsets: ["latin"], // Add subsets as needed
  weight: ["400", "600", "700"], // Specify weights
  style: ["normal", "italic"], // Specify styles
});

export const metadata: Metadata = {
  title: "save bite | home",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  // Ensure that the incoming `locale` is valid
  if (!routing.locales.includes(locale as any)) {
    notFound();
  }

  // Providing all messages to the client
  // side is the easiest way to get started
  const messages = await getMessages();
  return (
    <VerifyOTPProvider2>
      <VerifyOTPProvider>
        <html lang={locale} className={notoSans.className}>
          <body
            className={`antialiased min-h-screen`}
            suppressHydrationWarning={true}
          >
            <NextIntlClientProvider messages={messages}>
              {children}
            </NextIntlClientProvider>
          </body>
        </html>
      </VerifyOTPProvider>
    </VerifyOTPProvider2>
  );
}
