import Navbar from "@/components/features/Navbar";
import Sidebar from "@/components/features/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "save bite | login",
  description: "Generated by create next app",
};

export default function authLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={` min-h-screen`}>
      <Navbar />
      <Sidebar />
      {children}
    </div>
  );
}
