import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "save bite | home",
  description: "Generated by create next app",
};

export default function authLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return <div className={` min-h-screen`}>{children}</div>;
}
